"""Hydroperiod layer code contract (spec 2026-09-14, section 3.3)."""

from __future__ import annotations

HYDROPERIOD_OUTSIDE = 0
HYDROPERIOD_PERSISTENT = 1
HYDROPERIOD_SEASONAL = 2
HYDROPERIOD_MARGINAL = 3
HYDROPERIOD_UNOBSERVED = 4

HYDROPERIOD_CODES = frozenset(
    {
        HYDROPERIOD_OUTSIDE,
        HYDROPERIOD_PERSISTENT,
        HYDROPERIOD_SEASONAL,
        HYDROPERIOD_MARGINAL,
        HYDROPERIOD_UNOBSERVED,
    }
)

HYDROPERIOD_NAMES = {
    HYDROPERIOD_PERSISTENT: "persistent",
    HYDROPERIOD_SEASONAL: "seasonal",
    HYDROPERIOD_MARGINAL: "marginal",
    HYDROPERIOD_UNOBSERVED: "unobserved",
}

__all__ = [
    "HYDROPERIOD_CODES",
    "HYDROPERIOD_MARGINAL",
    "HYDROPERIOD_NAMES",
    "HYDROPERIOD_OUTSIDE",
    "HYDROPERIOD_PERSISTENT",
    "HYDROPERIOD_SEASONAL",
    "HYDROPERIOD_UNOBSERVED",
]
